/*
 * This file is generated by jOOQ.
 */
package io.github.lubosgarancovsky.aurora.repository.model.tables.records;


import io.github.lubosgarancovsky.aurora.repository.model.tables.Projects;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectsRecord extends UpdatableRecordImpl<ProjectsRecord> implements Record6<UUID, String, String, UUID, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.projects.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.projects.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.projects.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.projects.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.projects.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.projects.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.projects.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.projects.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.projects.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.projects.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.projects.code</code>.
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.projects.code</code>.
     */
    public String getCode() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, String, UUID, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, String, UUID, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Projects.PROJECTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Projects.PROJECTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Projects.PROJECTS.DESCRIPTION;
    }

    @Override
    public Field<UUID> field4() {
        return Projects.PROJECTS.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Projects.PROJECTS.CREATED_AT;
    }

    @Override
    public Field<String> field6() {
        return Projects.PROJECTS.CODE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public UUID component4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public String component6() {
        return getCode();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public UUID value4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public String value6() {
        return getCode();
    }

    @Override
    public ProjectsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ProjectsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProjectsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProjectsRecord value4(UUID value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ProjectsRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ProjectsRecord value6(String value) {
        setCode(value);
        return this;
    }

    @Override
    public ProjectsRecord values(UUID value1, String value2, String value3, UUID value4, LocalDateTime value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectsRecord
     */
    public ProjectsRecord() {
        super(Projects.PROJECTS);
    }

    /**
     * Create a detached, initialised ProjectsRecord
     */
    public ProjectsRecord(UUID id, String name, String description, UUID createdBy, LocalDateTime createdAt, String code) {
        super(Projects.PROJECTS);

        setId(id);
        setName(name);
        setDescription(description);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setCode(code);
        resetChangedOnNotNull();
    }
}
