/*
 * This file is generated by jOOQ.
 */
package io.github.lubosgarancovsky.aurora.repository.model.tables.records;


import io.github.lubosgarancovsky.aurora.repository.model.tables.Substories;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubstoriesRecord extends UpdatableRecordImpl<SubstoriesRecord> implements Record10<UUID, UUID, String, String, String, UUID, UUID, UUID, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.substories.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.substories.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.substories.parent_id</code>.
     */
    public void setParentId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.substories.parent_id</code>.
     */
    public UUID getParentId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.substories.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.substories.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.substories.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.substories.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.substories.code</code>.
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.substories.code</code>.
     */
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.substories.state_id</code>.
     */
    public void setStateId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.substories.state_id</code>.
     */
    public UUID getStateId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.substories.type_id</code>.
     */
    public void setTypeId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.substories.type_id</code>.
     */
    public UUID getTypeId() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.substories.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.substories.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.substories.assigned_to</code>.
     */
    public void setAssignedTo(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.substories.assigned_to</code>.
     */
    public UUID getAssignedTo() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.substories.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.substories.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, UUID, String, String, String, UUID, UUID, UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, UUID, String, String, String, UUID, UUID, UUID, UUID, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Substories.SUBSTORIES.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Substories.SUBSTORIES.PARENT_ID;
    }

    @Override
    public Field<String> field3() {
        return Substories.SUBSTORIES.NAME;
    }

    @Override
    public Field<String> field4() {
        return Substories.SUBSTORIES.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Substories.SUBSTORIES.CODE;
    }

    @Override
    public Field<UUID> field6() {
        return Substories.SUBSTORIES.STATE_ID;
    }

    @Override
    public Field<UUID> field7() {
        return Substories.SUBSTORIES.TYPE_ID;
    }

    @Override
    public Field<UUID> field8() {
        return Substories.SUBSTORIES.CREATED_BY;
    }

    @Override
    public Field<UUID> field9() {
        return Substories.SUBSTORIES.ASSIGNED_TO;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Substories.SUBSTORIES.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getParentId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getCode();
    }

    @Override
    public UUID component6() {
        return getStateId();
    }

    @Override
    public UUID component7() {
        return getTypeId();
    }

    @Override
    public UUID component8() {
        return getCreatedBy();
    }

    @Override
    public UUID component9() {
        return getAssignedTo();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getParentId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getCode();
    }

    @Override
    public UUID value6() {
        return getStateId();
    }

    @Override
    public UUID value7() {
        return getTypeId();
    }

    @Override
    public UUID value8() {
        return getCreatedBy();
    }

    @Override
    public UUID value9() {
        return getAssignedTo();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public SubstoriesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public SubstoriesRecord value2(UUID value) {
        setParentId(value);
        return this;
    }

    @Override
    public SubstoriesRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public SubstoriesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SubstoriesRecord value5(String value) {
        setCode(value);
        return this;
    }

    @Override
    public SubstoriesRecord value6(UUID value) {
        setStateId(value);
        return this;
    }

    @Override
    public SubstoriesRecord value7(UUID value) {
        setTypeId(value);
        return this;
    }

    @Override
    public SubstoriesRecord value8(UUID value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SubstoriesRecord value9(UUID value) {
        setAssignedTo(value);
        return this;
    }

    @Override
    public SubstoriesRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SubstoriesRecord values(UUID value1, UUID value2, String value3, String value4, String value5, UUID value6, UUID value7, UUID value8, UUID value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubstoriesRecord
     */
    public SubstoriesRecord() {
        super(Substories.SUBSTORIES);
    }

    /**
     * Create a detached, initialised SubstoriesRecord
     */
    public SubstoriesRecord(UUID id, UUID parentId, String name, String description, String code, UUID stateId, UUID typeId, UUID createdBy, UUID assignedTo, LocalDateTime createdAt) {
        super(Substories.SUBSTORIES);

        setId(id);
        setParentId(parentId);
        setName(name);
        setDescription(description);
        setCode(code);
        setStateId(stateId);
        setTypeId(typeId);
        setCreatedBy(createdBy);
        setAssignedTo(assignedTo);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
