/*
 * This file is generated by jOOQ.
 */
package io.github.lubosgarancovsky.aurora.repository.model;


import io.github.lubosgarancovsky.aurora.repository.model.tables.FlywaySchemaHistory;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Links;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Partners;
import io.github.lubosgarancovsky.aurora.repository.model.tables.ProjectBoard;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Projects;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Requests;
import io.github.lubosgarancovsky.aurora.repository.model.tables.StoryState;
import io.github.lubosgarancovsky.aurora.repository.model.tables.TeamPartner;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Teams;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.links</code>.
     */
    public final Links LINKS = Links.LINKS;

    /**
     * The table <code>public.partners</code>.
     */
    public final Partners PARTNERS = Partners.PARTNERS;

    /**
     * The table <code>public.project_board</code>.
     */
    public final ProjectBoard PROJECT_BOARD = ProjectBoard.PROJECT_BOARD;

    /**
     * The table <code>public.projects</code>.
     */
    public final Projects PROJECTS = Projects.PROJECTS;

    /**
     * The table <code>public.requests</code>.
     */
    public final Requests REQUESTS = Requests.REQUESTS;

    /**
     * The table <code>public.story_state</code>.
     */
    public final StoryState STORY_STATE = StoryState.STORY_STATE;

    /**
     * The table <code>public.team_partner</code>.
     */
    public final TeamPartner TEAM_PARTNER = TeamPartner.TEAM_PARTNER;

    /**
     * The table <code>public.teams</code>.
     */
    public final Teams TEAMS = Teams.TEAMS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Links.LINKS,
            Partners.PARTNERS,
            ProjectBoard.PROJECT_BOARD,
            Projects.PROJECTS,
            Requests.REQUESTS,
            StoryState.STORY_STATE,
            TeamPartner.TEAM_PARTNER,
            Teams.TEAMS
        );
    }
}
