/*
 * This file is generated by jOOQ.
 */
package io.github.lubosgarancovsky.aurora.repository.model;


import io.github.lubosgarancovsky.aurora.repository.model.tables.FlywaySchemaHistory;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Links;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Partners;
import io.github.lubosgarancovsky.aurora.repository.model.tables.ProjectBoard;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Projects;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Requests;
import io.github.lubosgarancovsky.aurora.repository.model.tables.StoryState;
import io.github.lubosgarancovsky.aurora.repository.model.tables.TeamPartner;
import io.github.lubosgarancovsky.aurora.repository.model.tables.Teams;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.links</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>public.partners</code>.
     */
    public static final Partners PARTNERS = Partners.PARTNERS;

    /**
     * The table <code>public.project_board</code>.
     */
    public static final ProjectBoard PROJECT_BOARD = ProjectBoard.PROJECT_BOARD;

    /**
     * The table <code>public.projects</code>.
     */
    public static final Projects PROJECTS = Projects.PROJECTS;

    /**
     * The table <code>public.requests</code>.
     */
    public static final Requests REQUESTS = Requests.REQUESTS;

    /**
     * The table <code>public.story_state</code>.
     */
    public static final StoryState STORY_STATE = StoryState.STORY_STATE;

    /**
     * The table <code>public.team_partner</code>.
     */
    public static final TeamPartner TEAM_PARTNER = TeamPartner.TEAM_PARTNER;

    /**
     * The table <code>public.teams</code>.
     */
    public static final Teams TEAMS = Teams.TEAMS;
}
