/*
 * This file is generated by jOOQ.
 */
package io.github.lubosgarancovsky.aurora.repository.model.tables;


import io.github.lubosgarancovsky.aurora.repository.model.Keys;
import io.github.lubosgarancovsky.aurora.repository.model.Public;
import io.github.lubosgarancovsky.aurora.repository.model.tables.records.ProjectBoardRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectBoard extends TableImpl<ProjectBoardRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.project_board</code>
     */
    public static final ProjectBoard PROJECT_BOARD = new ProjectBoard();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectBoardRecord> getRecordType() {
        return ProjectBoardRecord.class;
    }

    /**
     * The column <code>public.project_board.id</code>.
     */
    public final TableField<ProjectBoardRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.project_board.project_id</code>.
     */
    public final TableField<ProjectBoardRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.project_board.state_id</code>.
     */
    public final TableField<ProjectBoardRecord, UUID> STATE_ID = createField(DSL.name("state_id"), SQLDataType.UUID.nullable(false), this, "");

    private ProjectBoard(Name alias, Table<ProjectBoardRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProjectBoard(Name alias, Table<ProjectBoardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.project_board</code> table reference
     */
    public ProjectBoard(String alias) {
        this(DSL.name(alias), PROJECT_BOARD);
    }

    /**
     * Create an aliased <code>public.project_board</code> table reference
     */
    public ProjectBoard(Name alias) {
        this(alias, PROJECT_BOARD);
    }

    /**
     * Create a <code>public.project_board</code> table reference
     */
    public ProjectBoard() {
        this(DSL.name("project_board"), null);
    }

    public <O extends Record> ProjectBoard(Table<O> child, ForeignKey<O, ProjectBoardRecord> key) {
        super(child, key, PROJECT_BOARD);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ProjectBoardRecord> getPrimaryKey() {
        return Keys.PROJECT_BOARD_PKEY;
    }

    @Override
    public List<ForeignKey<ProjectBoardRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PROJECT_BOARD__PROJECT_BOARD_PROJECT_ID_FKEY, Keys.PROJECT_BOARD__PROJECT_BOARD_STATE_ID_FKEY);
    }

    private transient Projects _projects;
    private transient StoryState _storyState;

    /**
     * Get the implicit join path to the <code>public.projects</code> table.
     */
    public Projects projects() {
        if (_projects == null)
            _projects = new Projects(this, Keys.PROJECT_BOARD__PROJECT_BOARD_PROJECT_ID_FKEY);

        return _projects;
    }

    /**
     * Get the implicit join path to the <code>public.story_state</code> table.
     */
    public StoryState storyState() {
        if (_storyState == null)
            _storyState = new StoryState(this, Keys.PROJECT_BOARD__PROJECT_BOARD_STATE_ID_FKEY);

        return _storyState;
    }

    @Override
    public ProjectBoard as(String alias) {
        return new ProjectBoard(DSL.name(alias), this);
    }

    @Override
    public ProjectBoard as(Name alias) {
        return new ProjectBoard(alias, this);
    }

    @Override
    public ProjectBoard as(Table<?> alias) {
        return new ProjectBoard(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectBoard rename(String name) {
        return new ProjectBoard(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectBoard rename(Name name) {
        return new ProjectBoard(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectBoard rename(Table<?> name) {
        return new ProjectBoard(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
