/*
 * This file is generated by jOOQ.
 */
package io.github.lubosgarancovsky.aurora.repository.model.tables;


import io.github.lubosgarancovsky.aurora.repository.model.Keys;
import io.github.lubosgarancovsky.aurora.repository.model.Public;
import io.github.lubosgarancovsky.aurora.repository.model.tables.records.StoryTypeRecord;

import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoryType extends TableImpl<StoryTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.story_type</code>
     */
    public static final StoryType STORY_TYPE = new StoryType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoryTypeRecord> getRecordType() {
        return StoryTypeRecord.class;
    }

    /**
     * The column <code>public.story_type.id</code>.
     */
    public final TableField<StoryTypeRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.story_type.name</code>.
     */
    public final TableField<StoryTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.story_type.code</code>.
     */
    public final TableField<StoryTypeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    private StoryType(Name alias, Table<StoryTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private StoryType(Name alias, Table<StoryTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.story_type</code> table reference
     */
    public StoryType(String alias) {
        this(DSL.name(alias), STORY_TYPE);
    }

    /**
     * Create an aliased <code>public.story_type</code> table reference
     */
    public StoryType(Name alias) {
        this(alias, STORY_TYPE);
    }

    /**
     * Create a <code>public.story_type</code> table reference
     */
    public StoryType() {
        this(DSL.name("story_type"), null);
    }

    public <O extends Record> StoryType(Table<O> child, ForeignKey<O, StoryTypeRecord> key) {
        super(child, key, STORY_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<StoryTypeRecord> getPrimaryKey() {
        return Keys.STORY_TYPE_PKEY;
    }

    @Override
    public StoryType as(String alias) {
        return new StoryType(DSL.name(alias), this);
    }

    @Override
    public StoryType as(Name alias) {
        return new StoryType(alias, this);
    }

    @Override
    public StoryType as(Table<?> alias) {
        return new StoryType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryType rename(String name) {
        return new StoryType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryType rename(Name name) {
        return new StoryType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryType rename(Table<?> name) {
        return new StoryType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
