/*
 * This file is generated by jOOQ.
 */
package io.github.lubosgarancovsky.aurora.repository.model.tables;


import io.github.lubosgarancovsky.aurora.repository.model.Keys;
import io.github.lubosgarancovsky.aurora.repository.model.Public;
import io.github.lubosgarancovsky.aurora.repository.model.tables.records.StoryStateRecord;

import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoryState extends TableImpl<StoryStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.story_state</code>
     */
    public static final StoryState STORY_STATE = new StoryState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoryStateRecord> getRecordType() {
        return StoryStateRecord.class;
    }

    /**
     * The column <code>public.story_state.id</code>.
     */
    public final TableField<StoryStateRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.story_state.name</code>.
     */
    public final TableField<StoryStateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.story_state.code</code>.
     */
    public final TableField<StoryStateRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    private StoryState(Name alias, Table<StoryStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private StoryState(Name alias, Table<StoryStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.story_state</code> table reference
     */
    public StoryState(String alias) {
        this(DSL.name(alias), STORY_STATE);
    }

    /**
     * Create an aliased <code>public.story_state</code> table reference
     */
    public StoryState(Name alias) {
        this(alias, STORY_STATE);
    }

    /**
     * Create a <code>public.story_state</code> table reference
     */
    public StoryState() {
        this(DSL.name("story_state"), null);
    }

    public <O extends Record> StoryState(Table<O> child, ForeignKey<O, StoryStateRecord> key) {
        super(child, key, STORY_STATE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<StoryStateRecord> getPrimaryKey() {
        return Keys.STORY_STATE_PKEY;
    }

    @Override
    public StoryState as(String alias) {
        return new StoryState(DSL.name(alias), this);
    }

    @Override
    public StoryState as(Name alias) {
        return new StoryState(alias, this);
    }

    @Override
    public StoryState as(Table<?> alias) {
        return new StoryState(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryState rename(String name) {
        return new StoryState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryState rename(Name name) {
        return new StoryState(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryState rename(Table<?> name) {
        return new StoryState(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
